import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef } from "react";
import useSWRMutation from "swr/mutation";
import { useAuthToken } from "@/contexts/context";
import PostForm from "@/components/postForm";

export default function Modify() {
  // auth
  const accessToken = useAuthToken();

  // router
  const router = useRouter();

  // ref
  const formRef = useRef();

  // remote mutate
  const {
    data: post,
    trigger: modifyPost,
    error,
  } = useSWRMutation(
    `${process.env.API_URL}/post/${router.query.id}`,
    async (url, { arg }) => {
      const post = await fetch(url, {
        method: arg ? "PUT" : "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: arg,
      })
        .then((res) => res.json())
        .then((data) => data);

      if (!arg || post.errors) {
        return post;
      }

      // redirect
      router.push(`/post?id=${router.query.id}`);
    },
  );

  // fetch post
  useEffect(() => {
    if (accessToken) modifyPost();
  }, [accessToken]);

  // modify post
  const handleModifyPost = async (e) => {
    e.preventDefault();

    const formDate = new FormData(formRef.current);
    modifyPost(
      JSON.stringify({
        subject: formDate.get("subject"),
        content: formDate.get("content"),
      }),
    );
  };

  if (error) return <div>Failed to load</div>;
  if (!post) return <div></div>;

  return (
    <>
      <Head>
        <title>{post.subject}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostForm
          post={post}
          errors={post && post.errors}
          formRef={formRef}
          onClick={handleModifyPost}
        />
      </main>
    </>
  );
}
