import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef } from "react";
import useSWRMutation from "swr/mutation";
import { useAuthToken } from "@/contexts/context";
import ReplyForm from "@/components/replyForm";

export default function Modify() {
  // auth
  const accessToken = useAuthToken();

  // router
  const router = useRouter();

  // ref
  const formRef = useRef();

  // remote mutate
  const {
    data: reply,
    trigger: modifyReply,
    error,
  } = useSWRMutation(
    `${process.env.API_URL}/post/${router.query.post_id}/reply/${router.query.id}`,
    async (url, { arg }) => {
      const reply = await fetch(url, {
        method: arg ? "PUT" : "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: arg,
      })
        .then((res) => res.json())
        .then((data) => data);

      if (!arg || reply.errors) {
        return reply;
      }

      // redirect to list
      router.push(`/post?id=${router.query.post_id}`);
    },
  );

  // fetch reply
  useEffect(() => {
    if (accessToken) modifyReply();
  }, [accessToken]);

  // modify reply
  const handleModifyReply = async (e) => {
    e.preventDefault();

    const formDate = new FormData(formRef.current);
    modifyReply(JSON.stringify({ content: formDate.get("content") }));
  };

  if (error) return <div>Failed to load</div>;
  if (!reply) return <div></div>;

  return (
    <>
      <Head>
        <title>Modify the Reply</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ReplyForm
          reply={reply}
          errors={reply && reply.errors}
          formRef={formRef}
          onClick={handleModifyReply}
        />
      </main>
    </>
  );
}
